# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lidar_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10lidar_data.proto\x12\x04\x65nac\"d\n\x05Lidar\x12\x0e\n\x06nb_pts\x18\x01 \x01(\x05\x12\x17\n\x0f\x61ngle_increment\x18\x02 \x01(\x02\x12\x0e\n\x06\x61ngles\x18\x03 \x03(\x02\x12\x11\n\tdistances\x18\x04 \x03(\x02\x12\x0f\n\x07quality\x18\x05 \x03(\x02\"L\n\tProximity\x12\x18\n\x10\x63losest_distance\x18\x01 \x01(\x02\x12%\n\x06status\x18\x02 \x01(\x0e\x32\x15.enac.ProximityStatus\"/\n\tAmalgames\x12\t\n\x01x\x18\x01 \x03(\x02\x12\t\n\x01y\x18\x02 \x03(\x02\x12\x0c\n\x04size\x18\x03 \x03(\x02\".\n\x07\x42\x61lises\x12\r\n\x05index\x18\x01 \x03(\x05\x12\t\n\x01x\x18\x02 \x03(\x02\x12\t\n\x01y\x18\x03 \x03(\x02\"/\n\x08Position\x12\t\n\x01x\x18\x01 \x03(\x02\x12\t\n\x01y\x18\x02 \x03(\x02\x12\r\n\x05theta\x18\x03 \x03(\x02*0\n\x0fProximityStatus\x12\x06\n\x02OK\x10\x00\x12\x0b\n\x07WARNING\x10\x01\x12\x08\n\x04STOP\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lidar_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROXIMITYSTATUS._serialized_start=352
  _PROXIMITYSTATUS._serialized_end=400
  _LIDAR._serialized_start=26
  _LIDAR._serialized_end=126
  _PROXIMITY._serialized_start=128
  _PROXIMITY._serialized_end=204
  _AMALGAMES._serialized_start=206
  _AMALGAMES._serialized_end=253
  _BALISES._serialized_start=255
  _BALISES._serialized_end=301
  _POSITION._serialized_start=303
  _POSITION._serialized_end=350
# @@protoc_insertion_point(module_scope)
